### ISSUE TITLE
Entries are hidden in the feed after reading them

### ISSUE THREAD

**Issue by grolongo** [SqrtMinusOne/elfeed-summary#3]
Hello, first of all thank you for this package. I've started using it and it's exactly what I was missing after trying vanilla Elfeed and Elfeed-dashboard.

One thing confuses me though, I've both these variables set:

` (setq-default elfeed-search-filter "@6-months-ago")` for elfeed
` (setq elfeed-summary-default-filter "@6-months-ago ")` for elfeed-summary

I removed the `+unread` because I still want to see the entries listed in the feed even after I've read them, but the problem is that when I read an entry and go back it gets hidden because it has lost +unread tag, even if these variables are set.

**Comment by SqrtMinusOne** [comment]
Hello,

The default logic here is to show only unread entries if there's at least one such entry. You can set the following:
```elisp
(setq elfeed-summary--search-show-read t)
```
Then the package won't add `+unread`, regardless of that. Or you can open the feed with `M-RET` instead of `RET` in the summary buffer.

**Comment by grolongo** [comment]
My bad. I should have read the README further and notice the available bindings.
`M-RET` `elfeed-summary--action-show-read` is all I needed.

Thanks for the help.
