### ISSUE TITLE
Number of elements inside a feed isn't displayed properly

### ISSUE THREAD

**Issue by Kenneth-Mata** [SqrtMinusOne/elfeed-summary#4]
This happens in particular with the following feed, a[podcast](https://feeds.acast.com/public/shows/d1b39068-c10f-5817-8324-88ba173183cd), for some reason if shows a wrong number of entries in the preview and only counts as marked read those newest 85 entries, is not really a big issue but i guessed if was ok to bring up
![2022-07-08_20-43](https://user-images.githubusercontent.com/92641443/178083004-57ef9d73-7567-4ab7-9a88-f08dbb5531e5.png)
![2022-07-08_20-43_1](https://user-images.githubusercontent.com/92641443/178083010-8170a1f1-d590-4a21-acae-9cb6e1a860af.png)

**Comment by SqrtMinusOne** [comment]
What's your value of `elfeed-summary-look-back`? Is it

```lisp
(setq elfeed-summary-look-back (* 60 60 24 365 15))
```

**Comment by Kenneth-Mata** [comment]
> What's your value of `elfeed-summary-look-back`? Is it
> 
> ```lisp
> (setq elfeed-summary-look-back (* 60 60 24 365 15))
> ```

i'm very dumb, i had my last look-back number wrong, thanks.
